# Generated by Django 2.0.2 on 2018-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockcert', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='badge_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_image_file',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='criteria_narrative',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_id',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_logo_file',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_public_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_signature_file',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='issuer_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='revocation_list',
            field=models.URLField(default=''),
        ),
    ]
