# Generated by Django 2.0.2 on 2018-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockcert', '0003_auto_20180623_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='issuer_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issuer_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='revocation_list',
            field=models.CharField(default='', max_length=200),
        ),
    ]
