# Generated by Django 2.0.2 on 2018-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockcert', '0004_auto_20180624_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cert_image_file',
            field=models.ImageField(default='', upload_to='../static/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issuer_logo_file',
            field=models.ImageField(default='', upload_to='../static/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issuer_signature_file',
            field=models.ImageField(default='', upload_to='../static/images'),
        ),
    ]
